title: Go Vote Bangalore
email: help@blr.vote
description: |
  Bangalore needs more voters. Help us get there
  by signing up to vote today. We will help you
  get your Bangalore Voter ID.
url: "https://blr.vote"
# TODO: move to a github org
#github_username:  
sass:
  sass_dir: _scss
  quiet_deps: true